global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'maxa'
    static_configs:
      - targets: ['maxa:8000']

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
